# Generated by Django 2.0 on 2018-02-14 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('write', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wave',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='wave',
            name='description',
            field=models.CharField(max_length=300, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='wave',
            name='money',
            field=models.IntegerField(verbose_name='Сумма'),
        ),
    ]
