# Generated by Django 2.0 on 2018-02-14 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('write', '0002_auto_20180215_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wave',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
