# Generated by Django 2.0 on 2018-02-16 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('write', '0003_auto_20180215_0324'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaveType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='wave',
            name='wave_type',
            field=models.ForeignKey(null=True, on_delete=None, to='write.WaveType'),
        ),
    ]
