# Generated by Django 2.0 on 2018-02-16 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('write', '0004_auto_20180216_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wave',
            name='wave_type',
        ),
    ]
